"""Initial_db

Revision ID: d644c8ab04ed
Revises: 
Create Date: 2021-11-25 21:27:56.937803

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd644c8ab04ed'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('goal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), nullable=True),
    sa.Column('resume', sa.VARCHAR(length=255), nullable=True),
    sa.Column('goal_one', sa.VARCHAR(length=255), nullable=True),
    sa.Column('goal_two', sa.VARCHAR(length=255), nullable=True),
    sa.Column('goal_three', sa.VARCHAR(length=255), nullable=True),
    sa.Column('contact', sa.VARCHAR(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('goal')
    # ### end Alembic commands ###
